name: Backup to Google Drive

on:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Upload to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: my-file.txt
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          parent_folder_id: ${{ secrets.FOLDER_ID}}
