name: Backup to Google Drive

on:
  push:
    branches: [ main ]

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          filename: "my-file.txt"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "my-file.txt" # optional string
          overwrite: "true" # optional boolean

      - name: Delete local file
        run: |
          rm my-file.txt
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upload backup to google drive
