name: Backup to Google Drive

on:
  push:
    branches: [ main ]

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Current Date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -m ./backup/backup_${{ env.DATE }}.zip ./backup/*.sql

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          filename: "./backup/backup_${{ env.DATE }}.zip"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "backup_${{ env.DATE }}.zip" # optional string
          overwrite: "true" # optional boolean

      - name: Delete local file
        run: |
          rm -f ./backup/*.sql ./backup/*.zip

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upload backup to google drive
